server:
  port: "${SERVER_PORT:8080}"

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: "${DATABASE_URL}"
    username: "${DATABASE_USERNAME}"
    password: "${DATABASE_PASSWORD}"
  flyway:
    enabled: true
  data:
    redis:
      host: "${REDIS_HOST}"
      port: "${REDIS_PORT:6379}"

logging:
  level:
    root: INFO
    com.parazit.panel: INFO

app:
  database:
    url: "${DATABASE_URL}"
    username: "${DATABASE_USERNAME}"
    password: "${DATABASE_PASSWORD}"
  redis:
    host: "${REDIS_HOST}"
    port: "${REDIS_PORT:6379}"
  telegram:
    bot-token: "${BOT_TOKEN}"
  panel:
    url: "${PANEL_URL}"
    username: "${PANEL_USERNAME}"
    password: "${PANEL_PASSWORD}"
  payment:
    merchant-id: "${PAYMENT_MERCHANT_ID}"
