package com.parazit.panel.application.renewal;

public enum RenewalIneligibilityReason {
    RENEWAL_DISABLED,
    SUBSCRIPTION_NOT_FOUND,
    OWNERSHIP_MISMATCH,
    PROVISION_NOT_FOUND,
    PROVISIONING_IN_PROGRESS,
    PROVISIONING_FAILED,
    SUBSCRIPTION_REVOKED,
    SUBSCRIPTION_SUSPENDED,
    MISSING_REMOTE_CLIENT_REFERENCE,
    INVALID_EXPIRY,
    INVALID_TRAFFIC_STATE,
    PLAN_NOT_AVAILABLE,
    ALREADY_HAS_ACTIVE_RENEWAL_ORDER,
    UNKNOWN_STATE
}
